- name: app_setup
  ansible.builtin.import_role:
    name: "common"
    tasks_from: app-setup.yaml

- name: node_setup
  ansible.builtin.import_role:
    name: "common"
    tasks_from: nodejs-setup.yaml

- name: systemd_setup
  ansible.builtin.import_role:
    name: "common"
    tasks_from: systemd-setup.yaml