- name: app setup
  ansible.builtin.import_role:
    name: "common"
    tasks_from: app-setup.yaml

- name: install python3 packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: installed
  loop:
  - python3 
  - gcc 
  - python3-devel

- name: install dependencies
  ansible.builtin.pip:
    requirements: requirements.txt
    executable: pip3.9
  args:
    chdir: /app

- name: systemd setup
  ansible.builtin.import_role:
    name: "common"
    tasks_from: systemd-setup.yaml