- name: app setup
  ansible.builtin.import_role:
    name: "common"
    tasks_from: app-setup.yaml

- name: python setup
  ansible.builtin.import_role:
    name: "common"
    tasks_from: python-setup.yaml

- name: systemd setup
  ansible.builtin.import_role:
    name: "common"
    tasks_from: systemd-setup.yaml