- name: Install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: enable and start mysql
  ansible.builtin.service:
    name: mysqld
    enabled: yes
    state: started

- name: setting root password to mysql 
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ MYSQL_ROOT_PASSWORD }}" 