- name: "create service file for {{ component }}"
  ansible.builtin.copy:
    src: "{{ component }}.service.j2"
    dest: "/etc/systemd/system/{{ component }}.service"
  
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: "start and enable {{ component }}"
  ansible.builtin.service:
    name: "{{ component }}"
    enabled: yes
    state: restarted